### ISSUE TITLE
Wetterstation RF abhören

### ISSUE THREAD

**Issue by BLiHSBO** [HS-BO-Rooftop/monorepo#16]
Die Wetterstationen setzen auf ein Empfangsgerät welches die Wetterdaten empfängt und über WiFi in eine Cloud übermittelt.
Diese Lösung könnte man durch eine Eigenentwicklung ersetzen, welche den Funk abhört und auswertet und die Daten an unseren MQTT Broker übermittelt.
Implementierbar als Script auf dem Raspberry, oder als Teil des Dataloggers mit einem 433 MHz Funkmoduls

**Comment by BenjaminLindHSBO** [comment]
Modell: WH2900
http://www.foshk.com/Wifi_Weather_Station/WH2900.html
https://www.chilitec-static.de/22515.pdf?1531636259107

Platine (wahrscheinlich) diese:
https://fccid.io/WA5WH2902/Internal-Photos/09-WH2902-IntPho-3266679
