### ISSUE TITLE
WiFi Manager

### ISSUE THREAD

**Issue by Legincy** [HS-BO-Rooftop/monorepo#20]
Board macht AP auf, wenn es kein WLAN hat.
Dort kann dann SSID, PW eingegeben werden.
Dann werden die Einstellungen gespeichert.

**Comment by Legincy** [comment]
- [[d3fe58c](https://github.com/HS-BO-Rooftop/monorepo/commit/d3fe58c2d25cc464f1856d660a22e0b82fd6fb22)] Der WiFi-Manager wurde schonmal grob implementiert. Es wird ein Access Point erstellt und die Daten werden mit einem POST Request an den Datacollector weitergegen.

- [[a55bb6](https://github.com/HS-BO-Rooftop/monorepo/commit/a55bb6f7679acbd5554be75673fba0b6b239534a)] Es existiert eine custom Oberfläche, für die Eingabe der WiFi Daten des Zielnetzwerks. In der Oberfläche werden die Daten bereits validiert.

**Comment by Flusinerd** [comment]
Wie handhaben wir das, wenn keine Verbindung hergestellt werden konnte es aber Daten gibt? Nach wieviel Zeit / Versuchen brechen wir ab?

Versuchen wir es später erneut?

**Comment by Flusinerd** [comment]
Kann der ESP AP und Client gleichzeitig sein? Hab das nicht mehr ganz in Erinnerung. Ich meine schon. Dann kann man ja im Hintergrund einfach weiter versuchen.
