### ISSUE TITLE
UUID Handling

### ISSUE THREAD

**Issue by Legincy** [HS-BO-Rooftop/monorepo#24]
Sofern der Datacollector keine UUID besitzen sollte, soll sich dieser bei der Cloud melden und registrieren.
Die erhaltene UUID soll anschließend in das EEPORM geschrieben werden und für zukünftige Requests genutzt werden.

**Comment by Flusinerd** [comment]
```
POST /api/boards
```

**Comment by Flusinerd** [comment]
#26
