### ISSUE TITLE
Datacollector board issues

### ISSUE THREAD

**Issue by Flusinerd** [HS-BO-Rooftop/monorepo#28]
- [ ] SS 1 liegt auf GPIO35 -> Input Only Pin.
- [ ] GPIO Pinne -> Wir haben keine GPIO Pinne auf die wir zugreifen können (Auf I/O achten)

**Comment by Legincy** [comment]
Aktuell ist eine neue Revision mit folgenden Änderungen geplant: 

- [ ] Weitere 6 GPIO Pins die auf das Board sollen um die Entwicklung mit speziellen Sensoren und Aktoren zu ermöglichen. Folgende Pins würden zur Auswahl stehen (27, 28, 30, 31, 33, 36, 37, 8, 9) 
- [ ] SS1/2 werden von Pin 7 und 8 -> 10 und 11 gelegt, da Pin 7 (GPIO 35) ein Input Pin ist.
- [ ] Eine Idee war es den ADC wegzulassen, da der ESP einen Onboard besitzt. Dieser ist jedoch in den meisten Fällen sehr ungenau und verfälscht für essentiell wichtige Sensoren in unserem Projekt die Daten (Kapazitiver Feuchtigkeitssensor).
   * [Mikrocontroller.net Report](https://www.mikrocontroller.net/topic/476050)
   * [Arduino Report]( https://forum.arduino.cc/t/spannungsmessung-esp32-ungenau/911420/8)
- [ ] Boardgröße wird minimal angepasst, da der Abstand von den Buttons zu der SSD1306 Platine zu gering ist.
- [ ] Pin Layout soll "aufgeräumt" werden, so dass diese an einem Bereich gemeinsam zugänglich sind und nicht wie aktuell auf dem gesamten Board verteilt sind.


**Zusätzlich:** 
Wie sieht es mit der Wetterstation auf dem Dach aus, gibt es eine Möglichkeit oder irgendwelche zusätzlichen Features, die wir auf dem Board hinzufügen können, damit die Station ebenfalls mit einem Board verbunden werden kann? @BLiHSBO

**Comment by BLiHSBO** [comment]
Eine Einbindung sehe ich nur per Funk, die Platine der Wetterstation gibt nichts her um die Daten anders abzugreifen. Da wir jetzt viele GPIOs einführen können beliebige Transceiver genutzt werden. Nach meiner Recherche gibt es Module welche ein serielles Protokoll oder ASK modulierte Datenströme benutzen. Seriell lässt sich mit zwei GPIOs per Software umsetzen, wir brauchen nicht extra die hardware-Schnittstelle benutzen, da wir geringe Datenraten haben. ASK als Modulation für die Empfangseite braucht nur einen In-GPIO und Masse.
