### ISSUE TITLE
Api - Anpassungen

### ISSUE THREAD

**Issue by Flusinerd** [HS-BO-Rooftop/monorepo#29]
- [x] Register Route -> Return only active configurations
- [x] Get Configurations -> Query-Param ``activeOnly`` 
- [x] MQTT Subscription 
    - [x] Verbindung zu MQTT aufbauen
    - [ ] MQTT Topics abbonieren
    - [ ] MQTT Sensordaten als SSE bereitstellen
- [x] Limitierung aktiver Konfigurationen auf 8 pro Board
- [x] Größt mögliche Response für @Legincy bereitstellen (Register Route)

**Comment by Flusinerd** [comment]
@Legincy Hab ich was vergessen?

**Comment by Legincy** [comment]
Nein das sollte eigentlich soweit passen, hier vielleicht noch ein paar weitere Gedanken.

### `/api/register`
- Aktuell erhält der Datacollector bei `"id": null` als Antwort lediglich die neue Device ID und einen aktuellen Unix Timestamp. Gut wäre es, wenn die Antwort identisch zu dem Fall ist, wenn der Server eine Device ID erhält, die in der Datenbank hinterlegt ist. 
`
{
"id": "dfc62898-b14e-4238-a936-09d43cd15c18",
  "name": "Test123",
  "last_seen_at": null,
  "plant_id": null,
  "bed_id": null,
  "plant": null,
  "bed": null,
  "configuration": [],
  "timestamp": 1666403878630
}
`
- Ist bereits klar, welchen Fehlercode der Datacollector erhält, wenn die angegebene Device ID nicht vorhanden/falsch ist? An der "Strategie" hatte sich nichts geändert, oder? 

     -> Sollte sich der Datacollector **automatisch** zurücksetzen und erneut auf die `/api/register` Route zugreifen mit `"id": null` oder muss man der Benutzer die Werkeinstellung manuell ausführen?  

### `/api/heartbeat`
- Datacollector meldet sich alle x Sekunden/Minuten beim Server, um vorerst den Status ("alive") mitzuteilen und eine Zeitsynchronisation durchzuführen.
**[ ! ] Die Zeit dafür müssen wir noch unbedingt festlegen. Aktuell arbeite ich mit 60 Sekunden, sprich du kannst alle ~65-70 Sekunden einen Request erwarten.**

**Comment by Flusinerd** [comment]
@Legincy 
[Hier](https://github.com/HS-BO-Rooftop/monorepo/files/9844489/largest.response.txt) einmal die größt mögliche Response.
Sensoren sind auf **10** aktive pro Board limitiert. Kann ich aber wenn es nötig ist auch noch runtersetzen.

Außerdem sind noch einige Felder drin die 255 Chars lang sein können. Kann ich bei Bedarf dann auch noch runtersetzen.
Brauchst du ``board.plant``? Falls nicht fällt das dann auch komplett raus
